version: '3'

services: 
  mongo:
    env_file: '.env'
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
      - './config/mongo_setup.sh:/docker-entrypoint-initdb.d/mongo_setup.sh'

  server:
    env_file: '.env'
    build: '.'
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - './logs/server:${APP_DIR}/logs'
    command: 'npm run serve'
    depends_on:
      - mongo

  osrm: 
    env_file: '.env'
    build: 
      context: .
      dockerfile: Dockerfile_OSRM
    ports: 
      - 5000:5000
    command: 'osrm-routed --algorithm mld /data/massachusetts-latest.osrm'

volumes:
  mongo_data:
