version: '3'

services: 
  server:
    env_file: ".env"
    build: '.'
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}" 
    volumes:
      - './src/server:/data/app/src'

  client:
    image: 'nginx:alpine'
    volumes: 
      - './src/client/build/:/data/www/'
      - './src/client/config/nginx.conf:/etc/nginx/conf.d/client.conf'
    ports:
      - '8888:80'

  mongo:
    image: 'mongo'
    ports: 
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'

volumes:
  mongo_data:
